[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@aave=lib/aave-v3-core/","@openzeppelin=lib/openzeppelin-contracts/"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
